---
name: Mockingbird
version: 2.5
main: ethaniccc\Mockingbird\Mockingbird
api: 3.15.0
mcpe-protocol: [408, 419, 422, 428]

permissions:
  mockingbird:
    children:
      mockingbird.alerts:
        description: Get Mockingbird anti-cheat alerts.
        default: op
      mockingbird.debug:
        description: Get Mockingbird debug messages in-game
        default: op
      mockingbird.logs:
        description: Get the anti-cheat logs of a player
        default: op
...
