---
name: Mockingbird
version: 2.7.0
main: ethaniccc\Mockingbird\Mockingbird
api: 5.34.0

permissions:
  mockingbird.alerts:
    description: Get Mockingbird anti-cheat alerts.
    default: op
  mockingbird.debug:
    description: Get Mockingbird debug messages in-game
    default: op
  mockingbird.logs:
    description: Get the anti-cheat logs of a player
    default: op
  mockingbird.bypass:
    description: Bypass all Mockingbird punishments
    default: op
...